### PR TITLE
OOB

### PR DESCRIPTION
**Pull request by JBanker2**
Corrected

### CODE REVIEW

**Review by carlmontanari — CHANGES_REQUESTED** [review]
fix yo shit fool

**Review by carlmontanari — CHANGES_REQUESTED** [review]
Overall looking tight, but a few changes please sir:

1- Don't upload the filled out .xls (just the public one with no data -- but make sure you've got the oob_mgmt section added to that!)

2- formatting in acipdt.py
          - status and id indents all wonky in required args dict
          - nit picky, but plz capitalize the 'p' in Pod in the Invalid arg (line 2667)

3- Ensure that the test text file from earlier is gone (it may be but I'm not 100% sure how to tell in this view)

4- please pretty print the son blob so indentation and all that is perfect (yay for ODC!)

**Comment by JBanker2** [comment]
Changes have been

**Comment by JBanker2** [comment]
corrected

**Comment by carlmontanari** [comment]
Merging OOB Mgmt into main branch.

**Pull request merged**
